name: Build PDF

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Texlive Environment
        uses: teatimeguest/setup-texlive-action@f047e6a93274944959597f16fd69b30beaf8eef4
        with:
          packages: >-
            scheme-minimal
            latex-bin
            babel-english
            contour
            enumitem
            etoolbox
            fancyhdr
            fontawesome5
            fontspec
            geometry
            hyperref
            infwarerr
            kvoptions
            luatexbase
            marvosym
            pdftexcmds
            preprint
            titlesec
            tools
            ulem
            xcharter
            xcolor

      - name: Build PDFs
        run: make BUILD_DIR=.

      - name: Get Date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Tag this commit
        run: |
          git --version
          git config user.name "GH Actions"
          git config user.email "<>"
          git status
          git tag -fa ${{ steps.date.outputs.date }} -m "${{ steps.date.outputs.date }}"
          git describe

      - name: Release
        run: |
          # Replace the pdf if the release exists, otherwise create the release
          gh release upload ${{ steps.date.outputs.date }} --clobber *.pdf
          if [ "$?" -ne "0" ]; then
            gh release create ${{ steps.date.outputs.date }} *.pdf
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
