name: Build PDF

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache tex
        id: cache-tex
        uses: actions/cache@v3
        env:
          cache-name: cache-tex
        with:
          path: ~/work/_actions/xu-cheng/latex-action
          key: tex

      - name: Build
        uses: xu-cheng/latex-action@8c9adec310ed05afa3650bd2727d1e71ca1dfd0d
        with:
          root_file: main.tex
          latexmk_use_lualatex: true

      - name: Get Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Make Filename
        id: filename
        run: echo "::set-output name=name::jonathan-zhang-${{ steps.date.outputs.date }}.pdf"

      - name: Rename PDF to my name and date
        run: mv main.pdf ${{ steps.filename.outputs.name }}

      - name: Tag with date
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ steps.date.outputs.date }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release PDF
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.filename.outputs.name }}
          tag_name: ${{ steps.date.outputs.date }}
