name: Build PDF

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OUTPUT_FILE: jonathan-zhang-${{ github.ref_name }}.pdf
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_lualatex: true
      - name: Rename PDF to my name and version
        run: mv main.pdf $OUTPUT_FILE
      - name: Release PDF
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.OUTPUT_FILE }}
