name: Build PDF

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_lualatex: true
      - name: Get Filename
        id: filename
        run: echo "::set-output name=name::jonathan-zhang-$(date +'%Y-%m-%d').pdf"
      - name: Rename PDF to my name and date
        run: mv main.pdf ${{ steps.filename.outputs.name }}
      - name: Release PDF
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.filename.outputs.name }}
