name: Build and release

on:
  push:
    paths:
      - 'data/*.toml'
      - 'src/*.tex'
      - '.github/workflows/release.yaml'

env:
  my_name: jonathan-zhang

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Setup Texlive Environment
        uses: teatimeguest/setup-texlive-action@d12a3c1385fbc2f10e16971f204daa705c63e34d # 3.3.0
        with:
          package-file: DEPENDS.txt

      - name: Setup Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f  # 5.1.1
        with:
          python-version: "3.11"

      - name: Build PDFs
        run: python build.py

      - name: Upload PDFs
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b
        with:
          name: "pdfs"
          path: ".build/*.pdf"

  generate-image:
    needs: build-pdf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Download PDFs
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: "pdfs"

      - name: Setup Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f  # 5.1.1
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Create PNG
        # Adjust this to whichever resume you want to display
        run: python -m pdf2png anon-*-backend-python.pdf main.png

      - name: Upload PNG
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b
        with:
          name: "pngs"
          path: "main.png"

  release:
    needs: generate-image
    runs-on: ubuntu-latest
    steps:
      - name: Get timestamp and date
        # funny timestamp format since git tags do not allow ':'
        run: echo "timestamp=$(date +'%Y-%m-%dT%H-%MZ' --utc)" >> "$GITHUB_ENV"

      - name: Checkout Repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Tag this commit
        run: |
          git --version
          git config user.name "GH Actions"
          git config user.email "<>"
          git status
          git tag -a $timestamp -m $timestamp
          git push origin $timestamp
          git describe

      - name: Download PDFs
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: "pdfs"

      - name: Download PNGs
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: "pngs"

      - name: Release
        run: |
          gh release create --title $timestamp --generate-notes $timestamp *.pdf main.png
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
