name: Build and release

on:
  push:
    paths:
      - 'src/*.tex'
      - '.github/workflows/release.yaml'

env:
  my_name: jonathan-zhang

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Setup Texlive Environment
        uses: teatimeguest/setup-texlive-action@e69e0852590264df4a35dbc6cc94009a2466a562 # 3.3.0
        with:
          package-file: DEPENDS.txt

      - name: Setup Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1  # 4.7.0
        with:
          python-version: "3.11"

      - name: Build PDFs
        run: python build.py

      - name: Upload PDFs
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: "pdfs"
          path: ".build/*.pdf"

  generate-image:
    needs: build-pdf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Download PDFs
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: "pdfs"

      - name: Setup Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1  # 4.7.0
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Create PNG
        # Adjust this to whichever resume you want to display
        run: python -m pdf2png jonathan-zhang-*-anon-swe.pdf main.png

      - name: Upload PNG
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: "pngs"
          path: "main.png"

  release:
    needs: generate-image
    runs-on: ubuntu-latest
    steps:
      - name: Get timestamp and date
        # funny timestamp format since git tags do not allow ':'
        run: echo "timestamp=$(date +'%Y-%m-%dT%H-%MZ' --utc)" >> "$GITHUB_ENV"

      - name: Checkout Repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Tag this commit
        run: |
          git --version
          git config user.name "GH Actions"
          git config user.email "<>"
          git status
          git tag -a $timestamp -m $timestamp
          git push origin $timestamp
          git describe

      - name: Download PDFs
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: "pdfs"

      - name: Download PNGs
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: "pngs"

      - name: Release
        run: |
          gh release create --title $timestamp --generate-notes $timestamp *.pdf main.png
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
