name: Build and release

on:
  push:
    paths:
      - 'data/*.toml'
      - 'src/*.tex'
      - '.github/workflows/release.yaml'

env:
  my_name: jonathan-zhang

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938

      - name: Setup Texlive Environment
        uses: teatimeguest/setup-texlive-action@f8403fbb8e38c28da59f550951b959f3bdf00608 # 3.3.0
        with:
          package-file: DEPENDS.txt

      - name: Setup Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  # 5.2.0
        with:
          python-version: "3.11"

      - name: Build PDFs
        run: python build.py

      - name: Upload PDFs
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874
        with:
          name: "pdfs"
          path: ".build/*.pdf"

  generate-image:
    needs: build-pdf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938

      - name: Download PDFs
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: "pdfs"

      - name: Setup Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  # 5.2.0
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Create PNG
        # Adjust this to whichever resume you want to display
        run: python -m pdf2png anon-*-backend-python.pdf main.png

      - name: Upload PNG
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874
        with:
          name: "pngs"
          path: "main.png"

  release:
    needs: generate-image
    runs-on: ubuntu-latest
    steps:
      - name: Get timestamp and date
        # funny timestamp format since git tags do not allow ':'
        run: echo "timestamp=$(date +'%Y-%m-%dT%H-%MZ' --utc)" >> "$GITHUB_ENV"

      - name: Checkout Repo
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938

      - name: Tag this commit
        run: |
          git --version
          git config user.name "GH Actions"
          git config user.email "<>"
          git status
          git tag -a $timestamp -m $timestamp
          git push origin $timestamp
          git describe

      - name: Download PDFs
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: "pdfs"

      - name: Download PNGs
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: "pngs"

      - name: Release
        run: |
          gh release create --title $timestamp --generate-notes $timestamp *.pdf main.png
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
